%define major	1
%define libname %mklibname torsocks %{major}
%define devname %mklibname -d torsocks

Name:              torsocks
Version:           1.3
Release:           1

Summary:           Use SOCKS-friendly applications with Tor
Group:             Networking/Other
License:           GPLv2+
URL:               https://code.google.com/p/torsocks

# Source0 is generated by running Source10, which pulls from the upstream
# version control repository.
Source0:           http://www.wangafu.net/~nickm/torsocks-1.3.tar.gz
Source1:           http://www.wangafu.net/~nickm/torsocks-1.3.tar.gz.asc
Source2:           https://raw.github.com/adrelanos/Whonix/stable/whonix_shared/usr/local/bin/uwt
Source3:           torsocks.bash_completion

%description
Torsocks allows you to use most SOCKS-friendly applications in a safe way
with Tor. It ensures that DNS requests are handled safely and explicitly
rejects UDP traffic from the application you're using.

%package -n     %{libname}
Summary:        Library for accessing TOR
Group:          System/Libraries

%description -n %{libname}
Torsocks allows you to use most SOCKS-friendly applications in a safe way
with Tor. It ensures that DNS requests are handled safely and explicitly
rejects UDP traffic from the application you're using.

%package -n     %{devname}
Summary:        Development files for %{name}
Group:          Development/C
Requires:       %{libname} = %{EVRD}
Provides:       %{name}-devel = %{EVRD}

%description -n %{devname}
This package includes the development files for %{name}.

%prep
%setup -q

%build
%configure
%make


%install
%makeinstall_std

# Remove extraneous files.
rm -f %{buildroot}%{_libdir}/torsocks/libtorsocks.{a,la}*
rm -f %{buildroot}%{_datadir}/DEBUG
rm -f %{buildroot}%{_datadir}/README*
rm -f %{buildroot}%{_datadir}/SOCKS*
rm -f %{buildroot}%{_datadir}/*.sh
rm -f %{buildroot}%{_datadir}/*.txt
rm -f %{buildroot}%{_datadir}/*.patch

# Include modified usewithtor to support setting proxy type, ip and port using
# cli parameters to prevent identity correlation through circuit sharing.
install -p -D -m 0755 %{SOURCE2} %{buildroot}%{_bindir}/uwt

# For bash completion.
install -p -D -m 0644 %{SOURCE3} \
    %{buildroot}%{_sysconfdir}/bash_completion.d/torsocks


%files
%config(noreplace) %{_sysconfdir}/bash_completion.d/torsocks
%config(noreplace) %{_sysconfdir}/torsocks.conf
%doc ChangeLog COPYING README
%{_bindir}/torsocks
%{_bindir}/usewithtor
%{_bindir}/uwt
%{_mandir}/man1/torsocks.1.*
%{_mandir}/man1/usewithtor.1.*
%{_mandir}/man5/torsocks.conf.5.*
%{_mandir}/man8/torsocks.8.*

%files -n %{libname}
%dir %{_libdir}/torsocks
%{_libdir}/torsocks/libtorsocks.so.%{major}*

%files -n %{devname}
%{_libdir}/torsocks/libtorsocks.so
