%define major	0
%define libname %mklibname torsocks %{major}
%define devname %mklibname -d torsocks

Name:              torsocks
Version:           2.3.0
Release:           2
Summary:           Use SOCKS-friendly applications with Tor
Group:             Networking/Other
License:           GPLv2+
URL:               https://gitweb.torproject.org/torsocks.git/

# Source0 is generated by running Source10, which pulls from the upstream
# version control repository.
Source0:	   https://github.com/dgoulet/torsocks/archive/v%{version}.tar.gz
Source2:           https://raw.github.com/adrelanos/Whonix/stable/whonix_shared/usr/local/bin/uwt
Source3:           torsocks.bash_completion

%description
Torsocks allows you to use most SOCKS-friendly applications in a safe way
with Tor. It ensures that DNS requests are handled safely and explicitly
rejects UDP traffic from the application you're using.

%package -n     %{libname}
Summary:        Library for accessing TOR
Group:          System/Libraries

%description -n %{libname}
Torsocks allows you to use most SOCKS-friendly applications in a safe way
with Tor. It ensures that DNS requests are handled safely and explicitly
rejects UDP traffic from the application you're using.

%package -n     %{devname}
Summary:        Development files for %{name}
Group:          Development/C
Requires:       %{libname} = %{EVRD}
Provides:       %{name}-devel = %{EVRD}

%description -n %{devname}
This package includes the development files for %{name}.

%prep
%setup -q

%build
autoreconf -fiv
%configure
%make


%install
%makeinstall_std

# Remove extraneous files.
rm -f %{buildroot}%{_libdir}/torsocks/libtorsocks.{a,la}*
rm -f %{buildroot}%{_datadir}/doc/%{name}/*
rm -f %{buildroot}%{_datadir}/doc/README*
rm -f %{buildroot}%{_datadir}/doc/SOCKS*
rm -f %{buildroot}%{_datadir}/*.sh
rm -f %{buildroot}%{_datadir}/*.txt
rm -f %{buildroot}%{_datadir}/doc/*.txt
rm -f %{buildroot}%{_datadir}/*.patch

# Include modified usewithtor to support setting proxy type, ip and port using
# cli parameters to prevent identity correlation through circuit sharing.
install -p -D -m 0755 %{SOURCE2} %{buildroot}%{_bindir}/uwt

# For bash completion.
install -p -D -m 0644 %{SOURCE3} \
    %{buildroot}%{_sysconfdir}/bash_completion.d/torsocks


%files
%config(noreplace) %{_sysconfdir}/bash_completion.d/torsocks
%config(noreplace) %{_sysconfdir}/tor/torsocks.conf
%{_bindir}/torsocks
%{_bindir}/uwt
%{_mandir}/man1/torsocks.1.*
%{_mandir}/man5/torsocks.conf.5.*
%{_mandir}/man8/torsocks.8.*

%files -n %{libname}
%dir %{_libdir}/torsocks
%{_libdir}/torsocks/libtorsocks.so.%{major}*

%files -n %{devname}
%{_libdir}/torsocks/libtorsocks.so
